export const CREATE_CONTACT_REQUEST = 'CREATE_CONTACT_REQUEST'
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS'
export const CREATE_CONTACT_FAIL = 'CREATE_CONTACT_FAIL'

export const CREATE_CONTACT = 'CREATE_CONTACT'